# Generated by Django 3.2.19 on 2023-06-29 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arenda_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='poster',
        ),
        migrations.AlterField(
            model_name='spaceimage',
            name='space',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='arenda_app.space'),
        ),
    ]
